fix: Fix deprecation warnings

diff --git a/.github/workflows/checkPlugin.yml b/.github/workflows/checkPlugin.yml
--- a/.github/workflows/checkPlugin.yml
+++ b/.github/workflows/checkPlugin.yml
@@ -20,11 +20,16 @@ jobs:
           java-version: '17'
 
       - name: Run Checks
-        run: ./gradlew check --stacktrace
+        uses: coactions/setup-xvfb@v1
+        with:
+          run: ./gradlew check --stacktrace
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
       - name: Verify Plugin
         run: ./gradlew verifyPlugin --stacktrace
-
-      - name: Run Plugin Verifier
-        run: ./gradlew runPluginVerifier --stacktrace
 
